(TeX-add-style-hook
 "hmc_Rakotonirina-Durand"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "10pt" "a4paper")))
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art10"
    "init"
    "defs"
    "color"
    "subcaption")
   (TeX-add-symbols
    "red")
   (LaTeX-add-labels
    "thm:ergodic"
    "algo:metropolis"
    "eq:hamiltonian-dyn"
    "rque:edo"
    "eq:edo"
    "eq:canonical-dist"
    "eq:hyp"
    "prop:conservation"
    "prop:compo"
    "lem:sol-inverse"
    "eq:ds_dz"
    "rque:Hbar"
    "prop:rev"
    "prop:vol"
    "algo:leapfrog"
    "def:flot_approche"
    "prop:vol_discret"
    "prop:rev-leapfrog"
    "algo:HMC-ideal"
    "prop:inv-ideal"
    "prop:rever_discret"
    "eq:Lambda1"
    "algo:HMC"
    "fig:normal"
    "fig:normal_autocor"
    "fig:gm"
    "fig:gm_autocor"
    "fig:bl"
    "fig:bl_autocor")
   (LaTeX-add-bibliographies
    "ref"))
 :latex)

